In [1]:
i = 0
while i < 10
    i+= 1
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [3]:
myfriends = ["Torsten", "Torben", "Dörte", "Gunther"]
i = 1
while i < 5
    println(myfriends[i])
    i += 1
end

Torsten
Torben
Dörte
Gunther


In [5]:
for i in myfriends
    println("Na $i, wie gehts dir?")
end

Na Torsten, wie gehts dir?
Na Torben, wie gehts dir?
Na Dörte, wie gehts dir?
Na Gunther, wie gehts dir?


In [7]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [12]:
test = 1:10
for i in test
    println(i)
end
println(typeof(test))

1
2
3
4
5
6
7
8
9
10
UnitRange{Int64}


In [14]:
m,n = 5,5

(5, 5)

In [16]:
A = zeros(m,n)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [17]:
for i in 1:m
    for j in 1:n
        A[i,j] = i + j
    end
end
A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [19]:
B = zeros(m,n)
for i in 1:m, j in 1:n
    B[i,j] = i + j
end
B

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [20]:
C = [i + j for i in 1:m, j in 1:n]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [22]:
torsten = "nett"
teufel = "böse";

In [26]:

for i in [marvin, torben]
    if i == "hübsch"
        println("Er ist offensichtlich nett wie ein Engel.")
    elseif i == "hässlich"
        println("Er ist offensichtlich böse wie ein Teufel.")
    else
        println("Er ist $i")
    end
end

Er ist offensichtlich nett wie ein Engel.
Er ist offensichtlich böse wie ein Teufel.


In [29]:
a = true
b = "True"
c = "Falase"
a ? b : c  # if a, then b, else c

"True"